version: '2'
services:
  site:
    build: ./site
    image: nick/site
    links:
      - db
    volumes:
      - ./site/app:/usr/src/app:ro
    environment:
      DOCKER_DEV: "True"

  nginx:
    restart: always
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "80:80"
      - "8080:8080"
    links:
      - site

  db:
    image: redis:latest
